language: python

python:
  - "3.4"

# install dependencies
install: "pip install -r dependencies.txt"

# create database
before_script:
  - psql -c 'create database testdb;' -U postgres

# run tests
script: python tests.py
script: bash travis.bash

# ignore push events to this branch
branches:
  except:
    - travis-ci
